import { DatabaseSchema, VideoItem } from './types.ts';

export const INITIAL_VIDEOS: VideoItem[] = [
  {
    id: "video_001",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    download_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    product_url: "https://shopee.com.br/product-smartwatch-ultra-series",
    affiliate_url: "https://s.shopee.com.br/vendex_smartwatch_ultra",
    title: "Smartwatch Ultra Pro 8 Serie 9 AMOLED",
    description: "Tela AMOLED infinita com monitoramento de saúde completo, bateria para 7 dias e resistente à água!",
    thumbnail_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80",
    allow_download: true,
    active: true,
    position: 1,
    tags: ["Eletrônicos", "Smartwatch", "Shopee", "Tecnologia", "Promoção"],
    price: "R$ 149,90",
    discount: "-48%",
    views: 1240,
    clicks: 342,
    downloads: 87,
    created_at: "2026-09-20T10:00:00Z",
    updated_at: "2026-09-23T08:00:00Z"
  },
  {
    id: "video_002",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    download_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    product_url: "https://shopee.com.br/product-fone-bluetooth-noise-cancelling",
    affiliate_url: "https://s.shopee.com.br/vendex_fone_anc_pro",
    title: "Fone Bluetooth ANC Cancelamento de Ruído",
    description: "Isolamento acústico ativo premium, graves profundos e estojo carregador com display digital de bateria.",
    thumbnail_url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
    allow_download: true,
    active: true,
    position: 2,
    tags: ["Áudio", "Fone", "Bluetooth", "Tech", "Shopee"],
    price: "R$ 89,90",
    discount: "-35%",
    views: 980,
    clicks: 215,
    downloads: 45,
    created_at: "2026-09-21T12:00:00Z",
    updated_at: "2026-09-23T08:00:00Z"
  },
  {
    id: "video_003",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    download_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    product_url: "https://shopee.com.br/product-mini-liquidificador-portatil-usb",
    affiliate_url: "https://s.shopee.com.br/vendex_mini_blend_usb",
    title: "Mini Liquidificador Portátil Recarregável USB 6 Lâminas",
    description: "Prepare shakes, sucos e vitaminas em segundos onde você estiver! Super potente e fácil de lavar.",
    thumbnail_url: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&auto=format&fit=crop&q=80",
    allow_download: true,
    active: true,
    position: 3,
    tags: ["Casa", "Cozinha", "Fitness", "Portátil", "Viral"],
    price: "R$ 49,90",
    discount: "-52%",
    views: 1850,
    clicks: 490,
    downloads: 120,
    created_at: "2026-09-21T14:30:00Z",
    updated_at: "2026-09-23T08:00:00Z"
  },
  {
    id: "video_004",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4",
    download_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4",
    product_url: "https://shopee.com.br/product-luminaria-led-rgb-sunset-lamp",
    affiliate_url: "https://s.shopee.com.br/vendex_sunset_lamp_rgb",
    title: "Luminária Sunset Lamp Projetor Pôr do Sol RGB",
    description: "Crie o clima aesthetic perfeito para seus vídeos, quarto e fotos com 16 cores e controle remoto.",
    thumbnail_url: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=600&auto=format&fit=crop&q=80",
    allow_download: false,
    active: true,
    position: 4,
    tags: ["Decoração", "Quarto", "Luz RGB", "TikTok", "Setup"],
    price: "R$ 39,90",
    discount: "-25%",
    views: 740,
    clicks: 160,
    downloads: 18,
    created_at: "2026-09-22T09:15:00Z",
    updated_at: "2026-09-23T08:00:00Z"
  },
  {
    id: "video_005",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    download_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    product_url: "https://shopee.com.br/product-mini-impressora-termica-portatil",
    affiliate_url: "https://s.shopee.com.br/vendex_mini_impressora",
    title: "Mini Impressora Térmica Sem Tinta Bluetooth Portátil",
    description: "Imprima fotos, lembretes, adesivos e recibos sem gastar com cartucho ou tinta. Conexão bluetooth instantânea!",
    thumbnail_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    allow_download: true,
    active: true,
    position: 5,
    tags: ["Papelaria", "Tech", "Impressora", "Shopee", "Estudos"],
    price: "R$ 78,50",
    discount: "-40%",
    views: 1110,
    clicks: 280,
    downloads: 62,
    created_at: "2026-09-22T16:45:00Z",
    updated_at: "2026-09-23T08:00:00Z"
  },
  {
    id: "video_006",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    download_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    product_url: "https://shopee.com.br/product-aspirador-robo-inteligente-3em1",
    affiliate_url: "https://s.shopee.com.br/vendex_robo_aspirador_3em1",
    title: "Robô Aspirador Inteligente 3 em 1 Varre, Aspira e Passa Pano",
    description: "Economize seu tempo na faxina! Sensores antiqueda, bateria duradoura e perfil ultrafino para limpar sob o sofá.",
    thumbnail_url: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80",
    allow_download: true,
    active: true,
    position: 6,
    tags: ["Casa", "Limpeza", "Robô", "Praticidade"],
    price: "R$ 199,00",
    discount: "-30%",
    views: 650,
    clicks: 140,
    downloads: 30,
    created_at: "2026-09-22T18:00:00Z",
    updated_at: "2026-09-23T08:00:00Z"
  },
  {
    id: "video_007",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    download_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    product_url: "https://shopee.com.br/product-croptop-brasil-feminino-viral",
    affiliate_url: "https://s.shopee.com.br/vendex_cropped_brasil",
    title: "Cropped Feminino Brasil Canelado Tendência",
    description: "Peça viral mais buscada da semana! Tecido canelado premium com elastano, caimento perfeito e cores vibrantes.",
    thumbnail_url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80",
    allow_download: true,
    active: true,
    position: 1, // High priority at the top
    tags: ["Moda", "Cropped", "Feminino", "Viral", "Fresquinho"],
    price: "R$ 34,90",
    discount: "-40%",
    views: 310,
    clicks: 89,
    downloads: 24,
    shares: 42,
    priority_release: true,
    priority_duration_hours: 24,
    priority_expires_at: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];

export const INITIAL_DATABASE: DatabaseSchema = {
  settings: {
    name: "VendeX",
    version: 1,
    updated_at: new Date().toISOString(),
    description: "Base de dados oficial do VendeX com backup automático"
  },
  priority_settings: {
    enabled: true,
    shares_required: 1,
    frequency: 'daily',
    duration_hours: 24,
    default_priority_hours: 24,
    system_message: 'Compartilhe 1 oferta por dia e desbloqueie os vídeos fresquinhos antes de todo mundo!'
  },
  videos: INITIAL_VIDEOS,
  shares: [],
  user_profiles: {}
};

